steps:
  # 1단계: Node.js 이미지를 사용하여 애플리케이션을 빌드합니다.
  - name: "node:16"
    entrypoint: "bash"
    args: ["-c", "npm install && npm run build"]

  # 2단계: App Engine에 배포합니다.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

# Cloud Build에서 사용할 로그 버킷을 설정합니다.
logs_bucket: gs://cloud-build-test-09

timeout: "1200s"
