steps:
  # 1단계: Node.js를 사용하여 애플리케이션을 빌드합니다.
  - name: "node:14"
    entrypoint: "bash"
    args: ["-c", "npm install && npm run build"]

  # 2단계: Docker 이미지를 빌드합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-responsive-0902', '.']

  # 3단계: Docker 이미지를 Google Container Registry에 푸시합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-responsive-0902']

# 빌드 후 생성될 이미지를 명시합니다.
images:
  - 'gcr.io/$PROJECT_ID/my-responsive-0902'

timeout: "1200s"


# Cloud Build에서 사용할 로그 버킷을 설정합니다. 이거 필수!!!
logs_bucket: gs://cloud-build-test-09

timeout: "1200s"
