steps:
  # 1단계: Node.js를 사용하여 앱을 빌드합니다.
  - name: "node:14"
    entrypoint: "bash"
    args: ["-c", "npm install && npm run build"]

  # 2단계: 빌드된 결과물을 Google Cloud Storage에 업로드합니다.
  - name: "google/cloud-sdk:alpine"
    entrypoint: "bash"
    args: ["-c", "gsutil -m rsync -r build gs://cloud-build-test-09"]

images:
  - "gcr.io/$PROJECT_ID/my-react-app"

timeout: "1200s"
